# Generated by Django 5.0.7 on 2024-07-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listToDo', '0002_alter_user_email_alter_user_hash_password_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
