# Generated by Django 5.0.7 on 2024-09-15 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listToDo', '0004_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.TextField(),
        ),
    ]
